services:
  gateway:
    platform: linux/amd64
    image: taotoxicboy/zookeeper-gateway-service:latest
    environment:
      RT_SECRET: JiZrdW9x2eYdPw3WXsmpbeL9ufCAcjig
      AT_SECRET: VgmBOirkrV6x179MeyStIN8jr2xWQVWx
      PORT: 4000
      AUTH_SERVICE_URL: auth-service:50022
      KEY_SERVICE_URL: apikey-service:5005
      CLIENT_URL: https://keeper.iaaaiksu.com
      EXCHANGE_SERVICE_URL: exchange-service:50052
      PREDICT_SERVICE_URL: prediction-service:50057
      RABBITMQ_URL: amqp://keeper.iaaaiksu:k@@per.1aaa1ksu@62.72.30.12:5672
      RABBITMQ_QUEUE_TX: order_tx_queue
      SOCIAL_REDIRECT: https://keeper.iaaaiksu.com/app
      NOTIFY_QUEUE: notification_queue
      GOOGLE_CLIENT_ID: 1085551212854-qt83lqnnsut8ljv5soifk8a1tcsm1nm7.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      GOOGLE_CALLBACK_URL: https://keeper.iaaaiksu.com/api/auth/google/callback
      ELASTICSEARCH_NODE: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - '4000:4000'
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '9200:9200'

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch

  auth-service:
    platform: linux/amd64
    image: taotoxicboy/zookeeper-auth-service:latest
    container_name: auth-service
    environment:
      GRPC_URL: auth-service:50022
      RT_SECRET: JiZrdW9x2eYdPw3WXsmpbeL9ufCAcjig
      AT_SECRET: VgmBOirkrV6x179MeyStIN8jr2xWQVWx
      REDIS_URL: redis
      REDIS_PORT: 6379
      MONGODB_URI: mongodb://hubKeeperAdmin:secure0984672855@82.112.231.165:40025/keeperhub?authSource=admin
      RABBITMQ_URL: amqp://keeper.iaaaiksu:k@@per.1aaa1ksu@62.72.30.12:5672
    ports: 
      - '50022:50022'
    restart: always

  mail-service:
    platform: linux/amd64
    image: taotoxicboy/zookeeper-mail-queue-service:latest
    environment:
      RABBITMQ_URL: amqp://keeper.iaaaiksu:k@@per.1aaa1ksu@62.72.30.12:5672
      USERNAME_EMAIL: lab.keeperhub@gmail.com
      PASSWORD_EMAIL: gxqd khne mwbt rhyy
      REDIS_URL: redis
      REDIS_PORT: 6379
      RESET_PASSWORD_URL: https://keeper.iaaaiksu/challenge
    restart: always

  apikey-service:
    container_name: apikey
    platform: linux/amd64
    image: taotoxicboy/zookeeper-key-service:latest
    environment:
      GRPC_URL: apikey-service:5005
      MONGODB_URI: mongodb://hubKeeperAdmin:secure0984672855@82.112.231.165:40025/keeperhub?authSource=admin
      EXCHANGE_SERVICE_URL: exchange-service:50052
    restart: always

  exchange-service:
    container_name: exchange
    platform: linux/amd64
    image: taotoxicboy/zookeeper-exchange:latest
    environment:
      GRPC_URL: exchange-service:50052
      KEY_SERVICE_URL: apikey-service:5005
      RABBITMQ_URL: amqp://keeper.iaaaiksu:k@@per.1aaa1ksu@62.72.30.12:5672
      RABBITMQ_QUEUE_TX: order_tx_queue
    restart: always

  go-tx-service:
    container_name: go-tx
    platform: linux/amd64
    image: lindermand/go-order-consumer-tx-service:latest
    environment:
      DB_HOST: 82.112.231.165
      DB_PORT: 5432
      DB_USER: keeperzoo
      DB_PASSWORD: zookeeperx222
      DB_NAME: order_keeper
      RABBITMQ_URL: amqp://keeper.iaaaiksu:k@@per.1aaa1ksu@62.72.30.12:5672
    restart: always

  go-cron-service:
    container_name: go-cron
    platform: linux/amd64
    image: lindermand/go-order-cronjob-service:latest
    environment:
      DB_HOST: 82.112.231.165
      DB_PORT: 5432
      DB_USER: keeperzoo
      DB_PASSWORD: zookeeperx222
      DB_NAME: order_keeper
      RABBITMQ_URL: amqp://keeper.iaaaiksu:k@@per.1aaa1ksu@62.72.30.12:5672 
    restart: always

  prediction-service:
    container_name: prediction-service
    image: lindermand/predict-service:1.9
    command: python main.py
    environment:
      MONGO_URL: mongodb://hubKeeperAdmin:secure0984672855@82.112.231.165:40025/keeperhub?authSource=admin
      HOST_REDIS: redis
      PORT_REDIS: 6379
      PORT: 50057
      API_KEY: ZIIJYaRgR9WyJaKxq7zVehOtkfomjyX29NwNLWLlBgE3ikw5jtkMxVQD0IgewUxQ
      SECRET_KEY: 7JmVNUuzOSyjzDnzGsewBIszScuj47sf1w7MRNDUaRj8pE49gAX4fsgP9RlDCi6S       
    restart: always

  notification-service:
    container_name: notification-service
    image: taotoxicboy/zookeeper-notification-service:latest
    environment:
      RABBITMQ_URL: amqp://keeper.iaaaiksu:k@@per.1aaa1ksu@62.72.30.12:5672
      USERNAME_EMAIL: themanpoolbot@gmail.com
      PASSWORD_EMAIL: jvpp fujd ecvy pifo
      AUTH_SERVICE_URL: auth-service:50022
      NOTIFY_QUEUE: notification_queue
      MONGODB_URI: mongodb://hubKeeperAdmin:secure0984672855@82.112.231.165:40025/keeperhub?authSource=admin
    restart: always

  order-queue-service:
    container_name: order-queue
    image: taotoxicboy/order-queue:latest
    environment:
      RABBITMQ_URL: amqp://keeper.iaaaiksu:k@@per.1aaa1ksu@62.72.30.12:5672
      EXCHANGE_SERVICE_URL: exchange-service:50052
      NOTIFY_QUEUE: notification_queue
      RABBITMQ_QUEUE_TX: order_tx_queue
    restart: always

  # app:
  #   container_name: next-app
  #   image: lindermand/next14-keeper:latest
  #   ports:
  #     - '3000:3000'

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    restart: always