import type { Metadata } from "next";
import "./globals.css";
import theme from "./_components/theme/theme";
import { ThemeProvider } from "@mui/material";
import QueryProvider from "./_components/utility/queryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>
          <QueryProvider>
            <ThemeProvider theme={theme}>
              {children}
            </ThemeProvider>
          </QueryProvider>
        </main>
      </body>
    </html>
  );
}

