import type { Metadata } from 'next'
import './globals.css'
import { ThemeProvider } from '@mui/material'
import theme from './components/theme/theme'
import QueryProvider from './components/utilities/QueryProvider'
import StoreProvider from './components/utilities/StoreProvider'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body>
                <main>
                    <StoreProvider>
                        <QueryProvider>
                            <ThemeProvider theme={theme}>
                                {children}
                            </ThemeProvider>
                        </QueryProvider>
                    </StoreProvider>
                </main>
            </body>
        </html>
    )
}
